name: "Wait for Heroku"
description: "Wait for Heroku Deploy Preview to complete"
branding:
  icon: "clock"
  color: "blue"
inputs:
  site_name:
    description: "The Heroku site name to test against"
    required: true
  request_headers:
    description: "Stringified HTTP Header object key/value pairs to send in requests"
    required: false
  max_timeout:
    description: "The max time to run the action"
    required: false
  username:
    description: "Basic auth username"
    required: false
  password:
    description: "Basic auth password"
    required: false
outputs:
  url:
    description: "The fully qualified deploy preview URL"
runs:
  using: "node12"
  main: "index.js"
